import { z } from 'zod';

// Control characters other than tab and newline have no place in form input
// and are a common vector for log injection and broken CSV exports.
const CONTROL_CHARS = /[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F\u200B-\u200F\u2028\u2029\uFEFF]/g;

function clean(value: string): string {
  return value.normalize('NFC').replace(CONTROL_CHARS, '');
}

/** A single line of text: trimmed, inner whitespace collapsed. */
export function line(label: string, max: number, min = 1) {
  return z
    .string({ error: `${label} is required.` })
    .transform((value) => clean(value).replace(/\s+/g, ' ').trim())
    .pipe(
      z
        .string()
        .min(min, min <= 1 ? `${label} is required.` : `${label} must be at least ${min} characters.`)
        .max(max, `${label} must be at most ${max} characters.`),
    );
}

/** An optional single line; empty strings become undefined. */
export function optionalLine(label: string, max: number) {
  return z
    .string()
    .transform((value) => clean(value).replace(/\s+/g, ' ').trim())
    .pipe(z.string().max(max, `${label} must be at most ${max} characters.`))
    .transform((value) => (value === '' ? undefined : value))
    .optional()
    .nullable()
    .transform((value) => value ?? undefined);
}

/** Free text that keeps its line breaks. */
export function paragraph(label: string, max: number, min = 1) {
  return z
    .string({ error: `${label} is required.` })
    .transform((value) =>
      clean(value)
        .replace(/\r\n?/g, '\n')
        .replace(/[ \t]+\n/g, '\n')
        .replace(/\n{3,}/g, '\n\n')
        .trim(),
    )
    .pipe(
      z
        .string()
        .min(min, min <= 1 ? `${label} is required.` : `${label} must be at least ${min} characters.`)
        .max(max, `${label} must be at most ${max} characters.`),
    );
}

export function optionalParagraph(label: string, max: number) {
  return paragraph(label, max, 0)
    .transform((value) => (value === '' ? undefined : value))
    .optional()
    .nullable()
    .transform((value) => value ?? undefined);
}

/**
 * For editing records: a field left out is unchanged, while a field sent
 * empty (or null) is cleared. Used where the console lets staff remove a value.
 */
export function clearableLine(label: string, max: number) {
  return z
    .string()
    .transform((value) => clean(value).replace(/\s+/g, ' ').trim())
    .pipe(z.string().max(max, `${label} must be at most ${max} characters.`))
    .nullable()
    .optional()
    .transform((value) => (value === undefined ? undefined : value || null));
}

export function clearableParagraph(label: string, max: number) {
  return paragraph(label, max, 0)
    .nullable()
    .optional()
    .transform((value) => (value === undefined ? undefined : value || null));
}

export const email = z
  .string({ error: 'Email is required.' })
  .transform((value) => clean(value).trim().toLowerCase())
  .pipe(z.email('Please enter a valid email address.').max(254, 'That email address is too long.'));

/** International phone numbers as people actually type them: +256 765 871 126, 0765-871126. */
export const phone = z
  .string()
  .transform((value) => clean(value).replace(/\s+/g, ' ').trim())
  .pipe(
    z
      .string()
      .max(32, 'That phone number is too long.')
      .refine(
        (value) => value === '' || (/^\+?[0-9 ()./-]+$/.test(value) && value.replace(/\D/g, '').length >= 7),
        'Please enter a valid phone number.',
      ),
  )
  .transform((value) => (value === '' ? undefined : value))
  .optional()
  .nullable()
  .transform((value) => value ?? undefined);

/**
 * Hidden form field that people never see and bots happily fill in.
 * Anything but an empty value marks the submission as automated.
 */
export const honeypot = z.string().max(500).optional();

/** Idempotency key generated by the browser for each submission attempt. */
export const clientRequestId = z.uuid('Invalid request id.').optional();
