export interface AcademicArchitectureSchool {
  readonly name: string;
  readonly departments: readonly string[];
}

export const ACADEMIC_SCHOOL_STRUCTURE_BY_COLLEGE_ID: Record<number, readonly AcademicArchitectureSchool[]> = {
  1: [
    { name: 'School of Pure Mathematics', departments: ['Department of Algebra', 'Department of Analysis', 'Department of Geometry & Topology'] },
    { name: 'School of Applied Mathematics', departments: ['Department of Differential Equations', 'Department of Applied Modelling', 'Department of Mathematical Methods'] },
    { name: 'School of Mathematical Modelling & Simulation', departments: ['Department of Computational Modelling', 'Department of Systems Simulation', 'Department of Optimization & Operations Research'] },
    { name: 'School of Computational Mathematics', departments: ['Department of Numerical Analysis', 'Department of Scientific Computing', 'Department of Algorithmic Mathematics'] },
  ],
  2: [
    { name: 'School of Physics', departments: ['Department of Theoretical Physics', 'Department of Experimental Physics', 'Department of Condensed Matter Physics'] },
    { name: 'School of Chemistry', departments: ['Department of Organic Chemistry', 'Department of Inorganic Chemistry', 'Department of Physical Chemistry'] },
    { name: 'School of Materials Physics', departments: ['Department of Solid-State Physics', 'Department of Nanomaterials', 'Department of Materials Characterization'] },
    { name: 'School of Theoretical & Experimental Sciences', departments: ['Department of Scientific Methods', 'Department of Instrumentation', 'Department of Laboratory Systems'] },
  ],
  3: [
    { name: 'School of Biological Sciences', departments: ['Department of Botany', 'Department of Zoology', 'Department of Ecology'] },
    { name: 'School of Biotechnology', departments: ['Department of Molecular Biotechnology', 'Department of Industrial Biotechnology', 'Department of Bioprocess Engineering'] },
    { name: 'School of Microbial Sciences', departments: ['Department of Microbiology', 'Department of Virology', 'Department of Immunology'] },
    { name: 'School of Genomics & Systems Biology', departments: ['Department of Genomics', 'Department of Bioinformatics', 'Department of Systems Biology'] },
  ],
  4: [
    { name: 'School of Earth Systems Science', departments: ['Department of Earth Systems Analysis', 'Department of Environmental Systems', 'Department of Geospatial Systems'] },
    { name: 'School of Geology', departments: ['Department of Structural Geology', 'Department of Sedimentology', 'Department of Mineral Resources'] },
    { name: 'School of Geophysics', departments: ['Department of Seismology', 'Department of Exploration Geophysics', 'Department of Applied Geophysics'] },
    { name: 'School of Atmospheric & Climate Systems', departments: ['Department of Meteorology', 'Department of Climate Dynamics', 'Department of Atmospheric Physics'] },
  ],
  5: [
    { name: 'School of Materials Science', departments: ['Department of Materials Chemistry', 'Department of Materials Physics', 'Department of Materials Engineering'] },
    { name: 'School of Metallurgical Engineering', departments: ['Department of Extractive Metallurgy', 'Department of Physical Metallurgy', 'Department of Metallurgical Processing'] },
    { name: 'School of Advanced Manufacturing Systems', departments: ['Department of Manufacturing Engineering', 'Department of Production Systems', 'Department of Industrial Automation'] },
    { name: 'School of Industrial Materials & Processing', departments: ['Department of Materials Processing', 'Department of Industrial Fabrication', 'Department of Process Engineering'] },
  ],
  6: [
    { name: 'School of Crop Sciences', departments: ['Department of Agronomy', 'Department of Crop Protection', 'Department of Soil Science'] },
    { name: 'School of Animal & Livestock Systems', departments: ['Department of Animal Production', 'Department of Veterinary Systems', 'Department of Livestock Management'] },
    { name: 'School of Agroecology & Climate Systems', departments: ['Department of Agroecology', 'Department of Climate-Smart Agriculture', 'Department of Sustainable Farming Systems'] },
    { name: 'School of Food Systems & Sovereignty', departments: ['Department of Food Systems', 'Department of Food Policy', 'Department of Food Security'] },
  ],
  7: [
    { name: 'School of Agribusiness Management', departments: ['Department of Agribusiness Strategy', 'Department of Agricultural Finance', 'Department of Farm Management'] },
    { name: 'School of Agricultural Economics', departments: ['Department of Agricultural Economics', 'Department of Rural Development', 'Department of Policy Analysis'] },
    { name: 'School of Food Value Chains', departments: ['Department of Value Chain Analysis', 'Department of Market Systems', 'Department of Agro-Trade'] },
    { name: 'School of Agro-Industrial Systems', departments: ['Department of Agro-Processing', 'Department of Industrial Agriculture', 'Department of Supply Systems'] },
  ],
  8: [
    { name: 'School of Food Science & Technology', departments: ['Department of Food Chemistry', 'Department of Food Engineering', 'Department of Food Microbiology'] },
    { name: 'School of Nutrition & Dietetics', departments: ['Department of Human Nutrition', 'Department of Clinical Nutrition', 'Department of Dietetics'] },
    { name: 'School of Food Processing & Safety', departments: ['Department of Food Processing', 'Department of Food Safety', 'Department of Quality Assurance'] },
    { name: 'School of Nutrition Security Systems', departments: ['Department of Nutrition Policy', 'Department of Food Security Systems', 'Department of Public Nutrition'] },
  ],
  9: [
    { name: 'School of Industrial Hemp Production', departments: ['Department of Hemp Agronomy', 'Department of Hemp Genetics', 'Department of Crop Systems'] },
    { name: 'School of Hemp Biotechnology', departments: ['Department of Molecular Hemp Science', 'Department of Hemp Bioengineering', 'Department of Cannabinoid Science'] },
    { name: 'School of Hemp Industrial Engineering', departments: ['Department of Hemp Materials', 'Department of Hemp Processing', 'Department of Industrial Applications'] },
    { name: 'School of Bio-Economy Systems', departments: ['Department of Circular Economy', 'Department of Bio-Industrial Systems', 'Department of Sustainable Materials'] },
  ],
  10: [
    { name: 'School of Medicine', departments: ['Department of Internal Medicine', 'Department of Surgery', 'Department of Pediatrics', 'Department of Obstetrics & Gynecology'] },
    { name: 'School of Nursing & Midwifery', departments: ['Department of Nursing Science', 'Department of Midwifery', 'Department of Community Nursing'] },
    { name: 'School of Public Health', departments: ['Department of Epidemiology', 'Department of Health Policy', 'Department of Environmental Health'] },
    { name: 'School of Clinical Sciences', departments: ['Department of Clinical Medicine', 'Department of Pathology', 'Department of Clinical Diagnostics'] },
    { name: 'School of Diagnostic & Imaging Sciences', departments: ['Department of Radiography', 'Department of Imaging Technology', 'Department of Diagnostic Systems'] },
  ],
  11: [
    { name: 'School of Pharmacy', departments: ['Department of Pharmaceutics', 'Department of Clinical Pharmacy', 'Department of Pharmacy Practice'] },
    { name: 'School of Pharmaceutical Sciences', departments: ['Department of Pharmaceutical Chemistry', 'Department of Pharmacognosy', 'Department of Drug Formulation'] },
    { name: 'School of Pharmacology', departments: ['Department of Pharmacodynamics', 'Department of Pharmacokinetics', 'Department of Toxicology'] },
    { name: 'School of Drug Development & Therapeutics', departments: ['Department of Drug Discovery', 'Department of Clinical Trials', 'Department of Therapeutic Systems'] },
  ],
  12: [
    { name: 'School of Biomedical Science', departments: ['Department of Human Biology', 'Department of Biomedical Systems', 'Department of Cellular Biology'] },
    { name: 'School of Medical Laboratory Science', departments: ['Department of Clinical Chemistry', 'Department of Hematology', 'Department of Microbiology'] },
    { name: 'School of Clinical Laboratory Systems', departments: ['Department of Laboratory Diagnostics', 'Department of Laboratory Management', 'Department of Laboratory Technology'] },
    { name: 'School of Biomedical Research', departments: ['Department of Experimental Medicine', 'Department of Translational Research', 'Department of Biomedical Innovation'] },
  ],
  13: [
    { name: 'School of Epidemiology', departments: ['Department of Infectious Disease Epidemiology', 'Department of Biostatistics', 'Department of Field Epidemiology'] },
    { name: 'School of Health Security', departments: ['Department of Global Health Security', 'Department of Health Risk Analysis', 'Department of Emergency Preparedness'] },
    { name: 'School of Disease Surveillance Systems', departments: ['Department of Surveillance Systems', 'Department of Data Intelligence', 'Department of Outbreak Response'] },
    { name: 'School of Global Health Systems', departments: ['Department of Health Systems', 'Department of Health Policy', 'Department of Health Governance'] },
  ],
  14: [
    { name: 'School of Civil & Structural Engineering', departments: ['Department of Structural Engineering', 'Department of Geotechnical Engineering', 'Department of Construction Engineering'] },
    { name: 'School of Mechanical Engineering', departments: ['Department of Thermofluids', 'Department of Solid Mechanics', 'Department of Mechanical Systems Design'] },
    { name: 'School of Electrical & Electronic Engineering', departments: ['Department of Power Systems', 'Department of Electronics Engineering', 'Department of Control Systems'] },
    { name: 'School of Mechatronics & Integrated Systems', departments: ['Department of Mechatronics Engineering', 'Department of Embedded Systems', 'Department of Systems Integration'] },
  ],
  15: [
    { name: 'School of Renewable Energy Engineering', departments: ['Department of Solar Energy Systems', 'Department of Wind & Hybrid Systems', 'Department of Energy Storage'] },
    { name: 'School of Petroleum Engineering', departments: ['Department of Reservoir Engineering', 'Department of Drilling Engineering', 'Department of Production Systems'] },
    { name: 'School of Mining Engineering', departments: ['Department of Mining Systems', 'Department of Mineral Processing', 'Department of Mine Safety'] },
    { name: 'School of Resource Systems & Policy', departments: ['Department of Resource Governance', 'Department of Extractive Economics', 'Department of Environmental Resource Management'] },
  ],
  16: [
    { name: 'School of Hydrology', departments: ['Department of Surface Hydrology', 'Department of Groundwater Systems', 'Department of Hydrological Modelling'] },
    { name: 'School of Water Resources Engineering', departments: ['Department of Hydraulic Engineering', 'Department of Water Infrastructure', 'Department of Irrigation Systems'] },
    { name: 'School of Sanitation & Public Health Engineering', departments: ['Department of Sanitation Engineering', 'Department of Wastewater Systems', 'Department of Public Health Engineering'] },
    { name: 'School of Water Systems Management', departments: ['Department of Water Governance', 'Department of Water Economics', 'Department of Water Policy'] },
  ],
  17: [
    { name: 'School of Computer Science', departments: ['Department of Algorithms & Data Structures', 'Department of Systems Programming', 'Department of Distributed Systems'] },
    { name: 'School of Software Engineering', departments: ['Department of Software Design', 'Department of Software Testing', 'Department of DevOps Systems'] },
    { name: 'School of Artificial Intelligence', departments: ['Department of Machine Learning', 'Department of Natural Language Processing', 'Department of Computer Vision'] },
    { name: 'School of Cybersecurity & Digital Forensics', departments: ['Department of Cybersecurity', 'Department of Digital Forensics', 'Department of Information Assurance'] },
    { name: 'School of Information Systems', departments: ['Department of Information Systems Management', 'Department of Enterprise Systems', 'Department of Digital Transformation'] },
  ],
  18: [
    { name: 'School of Robotics Engineering', departments: ['Department of Robotic Systems', 'Department of Autonomous Systems', 'Department of Robotic Design'] },
    { name: 'School of Automation Systems', departments: ['Department of Industrial Automation', 'Department of Process Control', 'Department of Smart Manufacturing'] },
    { name: 'School of Embedded Systems', departments: ['Department of Embedded Hardware', 'Department of Embedded Software', 'Department of IoT Systems'] },
    { name: 'School of Intelligent Systems', departments: ['Department of Intelligent Control', 'Department of Cognitive Systems', 'Department of AI Integration'] },
  ],
  19: [
    { name: 'School of Telecommunications Engineering', departments: ['Department of Wireless Systems', 'Department of Signal Processing', 'Department of Communication Networks'] },
    { name: 'School of Network Systems', departments: ['Department of Network Architecture', 'Department of Network Security', 'Department of Cloud Systems'] },
    { name: 'School of Digital Infrastructure Systems', departments: ['Department of Infrastructure Engineering', 'Department of Data Centers', 'Department of Systems Deployment'] },
    { name: 'School of Communication Systems', departments: ['Department of Digital Communication', 'Department of Optical Systems', 'Department of Satellite Communication'] },
  ],
  20: [
    { name: 'School of Statistics', departments: ['Department of Mathematical Statistics', 'Department of Applied Statistics', 'Department of Statistical Modelling'] },
    { name: 'School of Data Science', departments: ['Department of Data Analytics', 'Department of Big Data Systems', 'Department of Data Engineering'] },
    { name: 'School of Actuarial Science', departments: ['Department of Risk Modelling', 'Department of Insurance Mathematics', 'Department of Financial Risk'] },
    { name: 'School of Quantitative Modelling', departments: ['Department of Predictive Modelling', 'Department of Simulation Systems', 'Department of Optimization Analytics'] },
  ],
  21: [
    { name: 'School of Finance', departments: ['Department of Corporate Finance', 'Department of Investment Analysis', 'Department of Financial Management'] },
    { name: 'School of Banking Systems', departments: ['Department of Commercial Banking', 'Department of Central Banking', 'Department of Banking Technology'] },
    { name: 'School of Financial Technology (FinTech)', departments: ['Department of Digital Payments', 'Department of Blockchain Systems', 'Department of Financial Innovation'] },
    { name: 'School of Digital Economy Systems', departments: ['Department of Digital Markets', 'Department of Platform Economies', 'Department of Economic Systems Analysis'] },
  ],
  22: [
    { name: 'School of Business Administration', departments: ['Department of Business Strategy', 'Department of Operations Management', 'Department of Marketing'] },
    { name: 'School of Management Studies', departments: ['Department of Organizational Behavior', 'Department of Strategic Management', 'Department of Human Resource Management'] },
    { name: 'School of Accounting', departments: ['Department of Financial Accounting', 'Department of Management Accounting', 'Department of Auditing'] },
    { name: 'School of Organizational Systems', departments: ['Department of Systems Management', 'Department of Institutional Design', 'Department of Organizational Analytics'] },
  ],
  23: [
    { name: 'School of Entrepreneurship', departments: ['Department of Venture Creation', 'Department of Small Business Systems', 'Department of Entrepreneurial Strategy'] },
    { name: 'School of Innovation Systems', departments: ['Department of Innovation Management', 'Department of Product Development', 'Department of Technology Innovation'] },
    { name: 'School of Startup Development', departments: ['Department of Startup Incubation', 'Department of Startup Finance', 'Department of Growth Systems'] },
    { name: 'School of Venture Systems', departments: ['Department of Venture Capital', 'Department of Startup Ecosystems', 'Department of Scaling Systems'] },
  ],
  24: [
    { name: 'School of Logistics', departments: ['Department of Logistics Management', 'Department of Transport Logistics', 'Department of Distribution Systems'] },
    { name: 'School of Supply Chain Systems', departments: ['Department of Supply Chain Design', 'Department of Procurement Systems', 'Department of Supply Chain Analytics'] },
    { name: 'School of International Trade', departments: ['Department of Trade Policy', 'Department of Trade Finance', 'Department of Export Systems'] },
    { name: 'School of Trade Systems', departments: ['Department of Market Systems', 'Department of Trade Infrastructure', 'Department of Trade Analytics'] },
  ],
  25: [
    { name: 'School of Law', departments: ['Department of Public Law', 'Department of Private Law', 'Department of International Law'] },
    { name: 'School of Legal Practice', departments: ['Department of Advocacy', 'Department of Legal Drafting', 'Department of Clinical Legal Education'] },
    { name: 'School of Justice Systems', departments: ['Department of Criminal Justice', 'Department of Judicial Systems', 'Department of Legal Institutions'] },
    { name: 'School of Correctional Systems', departments: ['Department of Corrections', 'Department of Rehabilitation Systems', 'Department of Penology'] },
  ],
  26: [
    { name: 'School of Cyber Law', departments: ['Department of Cybercrime Law', 'Department of Digital Rights', 'Department of Internet Governance'] },
    { name: 'School of Technology Law', departments: ['Department of Intellectual Property', 'Department of Technology Regulation', 'Department of Innovation Law'] },
    { name: 'School of Digital Regulation', departments: ['Department of Platform Regulation', 'Department of Data Protection', 'Department of Regulatory Systems'] },
    { name: 'School of Digital Governance', departments: ['Department of E-Government', 'Department of Digital Policy', 'Department of Governance Systems'] },
  ],
  27: [
    { name: 'School of Public Administration', departments: ['Department of Administrative Systems', 'Department of Public Service Management', 'Department of Local Government Systems'] },
    { name: 'School of Public Policy', departments: ['Department of Policy Analysis', 'Department of Policy Design', 'Department of Policy Evaluation'] },
    { name: 'School of Governance Systems', departments: ['Department of Governance Theory', 'Department of Institutional Systems', 'Department of Accountability Systems'] },
    { name: 'School of Institutional Reform', departments: ['Department of Public Sector Reform', 'Department of Anti-Corruption Systems', 'Department of Institutional Transformation'] },
  ],
  28: [
    { name: 'School of International Relations', departments: ['Department of Global Politics', 'Department of International Systems', 'Department of Regional Studies'] },
    { name: 'School of Diplomacy', departments: ['Department of Diplomatic Practice', 'Department of Negotiation Systems', 'Department of Foreign Service'] },
    { name: 'School of Global Governance', departments: ['Department of Multilateral Systems', 'Department of International Institutions', 'Department of Global Policy'] },
    { name: 'School of Foreign Policy Systems', departments: ['Department of Foreign Policy Analysis', 'Department of Strategic Diplomacy', 'Department of International Strategy'] },
  ],
  29: [
    { name: 'School of Security Studies', departments: ['Department of National Security', 'Department of Intelligence Studies', 'Department of Security Systems'] },
    { name: 'School of Peace & Conflict Studies', departments: ['Department of Conflict Analysis', 'Department of Peacebuilding', 'Department of Mediation Systems'] },
    { name: 'School of Strategic Studies', departments: ['Department of Strategic Analysis', 'Department of Geopolitics', 'Department of Military Strategy'] },
    { name: 'School of Defence & Intelligence Systems', departments: ['Department of Defence Systems', 'Department of Intelligence Operations', 'Department of Strategic Intelligence'] },
  ],
  30: [
    { name: 'School of Teacher Education', departments: ['Department of Primary Education', 'Department of Secondary Education', 'Department of Teacher Development'] },
    { name: 'School of Curriculum & Instruction', departments: ['Department of Curriculum Design', 'Department of Instructional Methods', 'Department of Learning Systems'] },
    { name: 'School of Educational Leadership', departments: ['Department of Education Management', 'Department of Leadership Systems', 'Department of Institutional Leadership'] },
    { name: 'School of Education Policy', departments: ['Department of Policy Systems', 'Department of Education Reform', 'Department of Education Planning'] },
  ],
  31: [
    { name: 'School of History', departments: ['Department of African History', 'Department of Global History', 'Department of Historiography'] },
    { name: 'School of Philosophy', departments: ['Department of Metaphysics', 'Department of Epistemology', 'Department of Ethics & Logic'] },
    { name: 'School of Civilisation Studies', departments: ['Department of Civilisational Analysis', 'Department of Comparative Civilisations', 'Department of Cultural Systems'] },
    { name: 'School of Cultural Systems', departments: ['Department of Cultural Studies', 'Department of Heritage Systems', 'Department of Identity & Society'] },
  ],
  32: [
    { name: 'School of Indigenous Knowledge Systems', departments: ['Department of Indigenous Sciences', 'Department of Traditional Knowledge Systems', 'Department of Knowledge Preservation'] },
    { name: 'School of African Epistemology', departments: ['Department of African Philosophy', 'Department of Knowledge Systems Theory', 'Department of Decolonial Epistemics'] },
    { name: 'School of Cultural Heritage Systems', departments: ['Department of Heritage Conservation', 'Department of Cultural Transmission', 'Department of Indigenous Practices'] },
    { name: 'School of Decolonial Studies', departments: ['Department of Decolonial Theory', 'Department of Liberation Studies', 'Department of Knowledge Sovereignty'] },
  ],
  33: [
    { name: 'School of Religion', departments: ['Department of Comparative Religion', 'Department of Religious Studies', 'Department of Theology'] },
    { name: 'School of Spiritual Systems', departments: ['Department of Spiritual Traditions', 'Department of African Spiritual Systems', 'Department of Consciousness Studies'] },
    { name: 'School of Ethics', departments: ['Department of Moral Philosophy', 'Department of Applied Ethics', 'Department of Bioethics'] },
    { name: 'School of Theology & Society', departments: ['Department of Systematic Theology', 'Department of Religion & Society', 'Department of Faith & Development'] },
  ],
  34: [
    { name: 'School of Linguistics', departments: ['Department of Theoretical Linguistics', 'Department of Applied Linguistics', 'Department of Sociolinguistics'] },
    { name: 'School of African Languages', departments: ['Department of Bantu Languages', 'Department of Nilotic Languages', 'Department of Afroasiatic Languages'] },
    { name: 'School of Translation', departments: ['Department of Translation Studies', 'Department of Technical Translation', 'Department of Literary Translation'] },
    { name: 'School of Interpretation Studies', departments: ['Department of Conference Interpretation', 'Department of Community Interpretation', 'Department of Language Mediation'] },
  ],
  35: [
    { name: 'School of Fine Arts', departments: ['Department of Painting', 'Department of Sculpture', 'Department of Visual Arts'] },
    { name: 'School of Music', departments: ['Department of Music Performance', 'Department of Music Theory', 'Department of Ethnomusicology'] },
    { name: 'School of Film & Media Arts', departments: ['Department of Film Production', 'Department of Cinematography', 'Department of Media Arts'] },
    { name: 'School of Creative Industries', departments: ['Department of Creative Entrepreneurship', 'Department of Cultural Production', 'Department of Arts Management'] },
  ],
  36: [
    { name: 'School of Journalism', departments: ['Department of News Reporting', 'Department of Investigative Journalism', 'Department of Broadcast Journalism'] },
    { name: 'School of Media Studies', departments: ['Department of Media Theory', 'Department of Media Analysis', 'Department of Audience Studies'] },
    { name: 'School of Strategic Communication', departments: ['Department of Public Relations', 'Department of Corporate Communication', 'Department of Political Communication'] },
    { name: 'School of Digital Media Systems', departments: ['Department of Digital Content Creation', 'Department of Social Media Systems', 'Department of Multimedia Production'] },
  ],
  37: [
    { name: 'School of Architecture', departments: ['Department of Architectural Design', 'Department of Urban Architecture', 'Department of Sustainable Architecture'] },
    { name: 'School of Quantity Surveying', departments: ['Department of Cost Engineering', 'Department of Construction Economics', 'Department of Project Cost Management'] },
    { name: 'School of Construction Management', departments: ['Department of Construction Planning', 'Department of Project Management', 'Department of Infrastructure Delivery'] },
    { name: 'School of Built Environment Systems', departments: ['Department of Built Environment Studies', 'Department of Infrastructure Systems', 'Department of Environmental Design'] },
  ],
  38: [
    { name: 'School of Urban Planning', departments: ['Department of Spatial Planning', 'Department of Land Use Planning', 'Department of Urban Development'] },
    { name: 'School of Smart Cities Systems', departments: ['Department of Smart Infrastructure', 'Department of Urban Technologies', 'Department of Digital Urban Systems'] },
    { name: 'School of Urban Innovation', departments: ['Department of Urban Design Innovation', 'Department of Sustainable Cities', 'Department of Urban Solutions'] },
    { name: 'School of Urban Governance', departments: ['Department of Urban Policy', 'Department of Municipal Systems', 'Department of City Governance'] },
  ],
  39: [
    { name: 'School of Environmental Science', departments: ['Department of Environmental Chemistry', 'Department of Environmental Physics', 'Department of Environmental Biology'] },
    { name: 'School of Ecology', departments: ['Department of Ecosystem Ecology', 'Department of Conservation Biology', 'Department of Biodiversity Systems'] },
    { name: 'School of Environmental Management', departments: ['Department of Environmental Planning', 'Department of Resource Management', 'Department of Environmental Impact Assessment'] },
    { name: 'School of Ecosystem Systems', departments: ['Department of Ecosystem Modelling', 'Department of Ecosystem Services', 'Department of Ecological Systems Analysis'] },
  ],
  40: [
    { name: 'School of Climate Science', departments: ['Department of Climate Modelling', 'Department of Atmospheric Science', 'Department of Climate Data Systems'] },
    { name: 'School of Sustainability Systems', departments: ['Department of Sustainable Development', 'Department of Resource Sustainability', 'Department of Circular Systems'] },
    { name: 'School of Climate Policy', departments: ['Department of Climate Policy Analysis', 'Department of Climate Law', 'Department of Policy Systems'] },
    { name: 'School of Climate Governance', departments: ['Department of Climate Governance Systems', 'Department of Institutional Frameworks', 'Department of Global Climate Systems'] },
  ],
  41: [
    { name: 'School of Climate Economics', departments: ['Department of Environmental Economics', 'Department of Climate Finance', 'Department of Economic Modelling'] },
    { name: 'School of Environmental Finance', departments: ['Department of Green Finance', 'Department of Sustainable Investment', 'Department of Financial Instruments'] },
    { name: 'School of Carbon Markets', departments: ['Department of Carbon Trading', 'Department of Emissions Accounting', 'Department of Carbon Policy'] },
    { name: 'School of Green Economy Systems', departments: ['Department of Green Growth', 'Department of Sustainable Markets', 'Department of Economic Transformation'] },
  ],
  42: [
    { name: 'School of Transport Engineering', departments: ['Department of Transport Infrastructure', 'Department of Traffic Engineering', 'Department of Transport Systems'] },
    { name: 'School of Mobility Systems', departments: ['Department of Mobility Planning', 'Department of Urban Mobility', 'Department of Intelligent Transport Systems'] },
    { name: 'School of Transport Planning', departments: ['Department of Transport Policy', 'Department of Transport Economics', 'Department of Planning Systems'] },
    { name: 'School of Transport Policy', departments: ['Department of Mobility Policy', 'Department of Regulatory Systems', 'Department of Transport Governance'] },
  ],
  43: [
    { name: 'School of Maritime Studies', departments: ['Department of Maritime Operations', 'Department of Navigation Systems', 'Department of Maritime Safety'] },
    { name: 'School of Blue Economy Systems', departments: ['Department of Ocean Economy', 'Department of Marine Resources', 'Department of Coastal Systems'] },
    { name: 'School of Ocean Systems', departments: ['Department of Oceanography', 'Department of Marine Science', 'Department of Ocean Engineering'] },
    { name: 'School of Marine Resource Management', departments: ['Department of Fisheries Systems', 'Department of Marine Conservation', 'Department of Resource Governance'] },
  ],
  44: [
    { name: 'School of Tourism Management', departments: ['Department of Tourism Systems', 'Department of Travel Management', 'Department of Destination Development'] },
    { name: 'School of Hospitality Systems', departments: ['Department of Hotel Management', 'Department of Hospitality Operations', 'Department of Service Systems'] },
    { name: 'School of Cultural Economy', departments: ['Department of Cultural Tourism', 'Department of Heritage Economy', 'Department of Creative Economy'] },
    { name: 'School of Destination Management', departments: ['Department of Destination Planning', 'Department of Tourism Policy', 'Department of Visitor Management'] },
  ],
  45: [
    { name: 'School of Sports Science', departments: ['Department of Sports Physiology', 'Department of Sports Biomechanics', 'Department of Sports Psychology'] },
    { name: 'School of Human Performance', departments: ['Department of Performance Analysis', 'Department of Strength & Conditioning', 'Department of Athletic Development'] },
    { name: 'School of Exercise Physiology', departments: ['Department of Exercise Science', 'Department of Health Fitness', 'Department of Rehabilitation Systems'] },
    { name: 'School of Sports Management', departments: ['Department of Sports Administration', 'Department of Sports Marketing', 'Department of Event Management'] },
  ],
  46: [
    { name: 'School of Psychology', departments: ['Department of Clinical Psychology', 'Department of Cognitive Psychology', 'Department of Social Psychology'] },
    { name: 'School of Counselling Psychology', departments: ['Department of Therapeutic Practice', 'Department of Mental Health Systems', 'Department of Psychosocial Support'] },
    { name: 'School of Human Development', departments: ['Department of Developmental Psychology', 'Department of Lifespan Development', 'Department of Human Growth'] },
    { name: 'School of Behavioural Systems', departments: ['Department of Behavioural Science', 'Department of Applied Behaviour Analysis', 'Department of Behavioural Research'] },
  ],
  47: [
    { name: 'School of Leadership Studies', departments: ['Department of Leadership Theory', 'Department of Strategic Leadership', 'Department of Political Leadership'] },
    { name: 'School of Human Capital Systems', departments: ['Department of Workforce Development', 'Department of Talent Systems', 'Department of Human Capital Analytics'] },
    { name: 'School of Organizational Leadership', departments: ['Department of Organizational Strategy', 'Department of Change Management', 'Department of Institutional Leadership'] },
    { name: 'School of Institutional Development', departments: ['Department of Institutional Systems', 'Department of Capacity Development', 'Department of Organizational Reform'] },
  ],
  48: [
    { name: 'School of Aerospace Engineering', departments: ['Department of Aerodynamics', 'Department of Propulsion Systems', 'Department of Aerospace Structures'] },
    { name: 'School of Space Systems', departments: ['Department of Space Engineering', 'Department of Orbital Mechanics', 'Department of Space Missions'] },
    { name: 'School of Satellite Systems', departments: ['Department of Satellite Engineering', 'Department of Satellite Communications', 'Department of Space Data Systems'] },
    { name: 'School of Remote Sensing Systems', departments: ['Department of Remote Sensing', 'Department of Geospatial Intelligence', 'Department of Earth Observation Systems'] },
  ],
  49: [
    { name: 'School of Futures Studies', departments: ['Department of Futures Theory', 'Department of Scenario Planning', 'Department of Trend Analysis'] },
    { name: 'School of Strategic Foresight', departments: ['Department of Foresight Systems', 'Department of Strategic Intelligence', 'Department of Predictive Systems'] },
    { name: 'School of Transformation Systems', departments: ['Department of Systems Transformation', 'Department of Innovation Systems', 'Department of Institutional Change'] },
    { name: 'School of Civilisational Futures', departments: ['Department of Civilisational Modelling', 'Department of Global Futures', 'Department of Strategic Transformation'] },
  ],
};

export const ACADEMIC_RESEARCH_INSTITUTES: readonly string[] = [
  'Institute for Pan-African Civilisational Systems',
  'Institute for Governance, Public Policy & Statecraft',
  'Institute for Law, Justice & Constitutional Development',
  'Institute for Security, Peace & Strategic Studies',
  'Institute for Diplomacy & Global Relations',
  'Institute for Leadership, Institutions & State Capacity',
  'Institute for Financial Systems & Economic Transformation',
  'Institute for Trade, Logistics & Industrial Systems',
  'Institute for Entrepreneurship, Innovation & Enterprise Systems',
  'Institute for Digital Economy & Platform Systems',
  'Institute for Agribusiness & Value Chain Systems',
  'Institute for Advanced Mathematical & Computational Systems',
  'Institute for Physical Sciences & Advanced Materials',
  'Institute for Engineering, Infrastructure & Industrial Systems',
  'Institute for Artificial Intelligence, Data & Digital Systems',
  'Institute for Robotics & Cyber-Physical Systems',
  'Institute for Telecommunications & Digital Infrastructure',
  'Institute for Space, Aerospace & Satellite Systems',
  'Institute for Medical Sciences & Clinical Research',
  'Institute for Public Health, Epidemiology & Health Security',
  'Institute for Pharmaceutical & Drug Development Systems',
  'Institute for Biomedical & Laboratory Systems',
  'Institute for Biotechnology & Genomic Systems',
  'Institute for Agriculture, Agroecology & Food Systems',
  'Institute for Food Science, Nutrition & Food Security',
  'Institute for Industrial Hemp & Bio-Economy Systems',
  'Institute for Earth Systems & Geosciences',
  'Institute for Climate Change & Sustainability Systems',
  'Institute for Climate Economy & Carbon Systems',
  'Institute for Environmental Science & Ecological Systems',
  'Institute for Water Systems, Hydrology & Sanitation',
  'Institute for Energy, Extractives & Resource Systems',
  'Institute for Architecture & Built Environment Systems',
  'Institute for Urban Futures & Smart Cities',
  'Institute for Transport & Mobility Systems',
  'Institute for Maritime & Blue Economy Systems',
  'Institute for Humanities & Civilisation Studies',
  'Institute for Indigenous Knowledge & Epistemic Systems',
  'Institute for Religion, Spirituality & Ethics',
  'Institute for Languages, Translation & Communication Systems',
  'Institute for Arts, Creative Industries & Cultural Systems',
  'Institute for Media, Communication & Information Systems',
  'Institute for Education Systems & Pedagogical Innovation',
  'Institute for Psychology, Behaviour & Human Development',
  'Institute for Sports Science & Human Performance',
  'Institute for Leadership & Human Capital Systems',
  'Institute for Tourism, Hospitality & Cultural Economy',
  'Institute for Futures, Foresight & Strategic Systems',
  'Institute for Civilisational Transformation & Global Systems',
] as const;

export const ACADEMIC_RESEARCH_INSTITUTES_BY_COLLEGE_ID: Record<number, string> = {
  1: 'Institute for Advanced Mathematical & Computational Systems',
  2: 'Institute for Physical Sciences & Advanced Materials',
  3: 'Institute for Biotechnology & Genomic Systems',
  4: 'Institute for Earth Systems & Geosciences',
  5: 'Institute for Physical Sciences & Advanced Materials',
  6: 'Institute for Agriculture, Agroecology & Food Systems',
  7: 'Institute for Agribusiness & Value Chain Systems',
  8: 'Institute for Food Science, Nutrition & Food Security',
  9: 'Institute for Industrial Hemp & Bio-Economy Systems',
  10: 'Institute for Medical Sciences & Clinical Research',
  11: 'Institute for Pharmaceutical & Drug Development Systems',
  12: 'Institute for Biomedical & Laboratory Systems',
  13: 'Institute for Public Health, Epidemiology & Health Security',
  14: 'Institute for Engineering, Infrastructure & Industrial Systems',
  15: 'Institute for Energy, Extractives & Resource Systems',
  16: 'Institute for Water Systems, Hydrology & Sanitation',
  17: 'Institute for Artificial Intelligence, Data & Digital Systems',
  18: 'Institute for Robotics & Cyber-Physical Systems',
  19: 'Institute for Telecommunications & Digital Infrastructure',
  20: 'Institute for Artificial Intelligence, Data & Digital Systems',
  21: 'Institute for Financial Systems & Economic Transformation',
  22: 'Institute for Entrepreneurship, Innovation & Enterprise Systems',
  23: 'Institute for Entrepreneurship, Innovation & Enterprise Systems',
  24: 'Institute for Trade, Logistics & Industrial Systems',
  25: 'Institute for Law, Justice & Constitutional Development',
  26: 'Institute for Law, Justice & Constitutional Development',
  27: 'Institute for Governance, Public Policy & Statecraft',
  28: 'Institute for Diplomacy & Global Relations',
  29: 'Institute for Security, Peace & Strategic Studies',
  30: 'Institute for Education Systems & Pedagogical Innovation',
  31: 'Institute for Pan-African Civilisational Systems',
  32: 'Institute for Indigenous Knowledge & Epistemic Systems',
  33: 'Institute for Religion, Spirituality & Ethics',
  34: 'Institute for Languages, Translation & Communication Systems',
  35: 'Institute for Arts, Creative Industries & Cultural Systems',
  36: 'Institute for Media, Communication & Information Systems',
  37: 'Institute for Architecture & Built Environment Systems',
  38: 'Institute for Urban Futures & Smart Cities',
  39: 'Institute for Environmental Science & Ecological Systems',
  40: 'Institute for Climate Change & Sustainability Systems',
  41: 'Institute for Climate Economy & Carbon Systems',
  42: 'Institute for Transport & Mobility Systems',
  43: 'Institute for Maritime & Blue Economy Systems',
  44: 'Institute for Tourism, Hospitality & Cultural Economy',
  45: 'Institute for Sports Science & Human Performance',
  46: 'Institute for Psychology, Behaviour & Human Development',
  47: 'Institute for Leadership & Human Capital Systems',
  48: 'Institute for Space, Aerospace & Satellite Systems',
  49: 'Institute for Futures, Foresight & Strategic Systems',
} as const;
