export interface StudentLifeGroup {
  readonly title: string;
  readonly subtitle?: string;
  readonly items: readonly string[];
}

export interface StudentLifeSystem {
  readonly id: 'cultural' | 'clubs' | 'professional';
  readonly label: string;
  readonly eyebrow: string;
  readonly title: string;
  readonly description: string;
  readonly governanceTitle: string;
  readonly governance: readonly string[];
  readonly groups: readonly StudentLifeGroup[];
}

export const STUDENT_LIFE_SYSTEMS: readonly StudentLifeSystem[] = [
  {
    id: 'cultural',
    label: 'Cultural Societies',
    eyebrow: 'Cultural and Heritage Societies',
    title: 'A continental cultural knowledge system.',
    description:
      'Identity preservation, cultural research, leadership formation, and intercultural integration organized under a Pan-African academic framework.',
    governanceTitle: 'Pan-African Cultural Union (PACU)',
    governance: [
      'Standardisation and oversight',
      'Cultural diplomacy and integration',
      'Heritage preservation and documentation',
      'Annual continental cultural programming',
    ],
    groups: [
      {
        title: 'Uganda Cultural Systems',
        subtitle: 'East African cultural societies',
        items: [
          'Baganda Cultural Society',
          'Basoga Cultural Society',
          'Banyankole Cultural Society',
          'Bakiga Cultural Society',
          'Batooro Cultural Society',
          'Banyoro Cultural Society',
          'Bafumbira Cultural Society',
          'Bakonjo Cultural Society',
          'Iteso Cultural Society',
          'Acholi Cultural Society',
          'Lango Cultural Society',
          'Alur Cultural Society',
          'Japadhola Cultural Society',
          'Lugbara Cultural Society',
        ],
      },
      {
        title: 'Karamoja Cultural Systems',
        subtitle: 'A multi-clan cultural ecosystem',
        items: [
          'Jie Cultural Society',
          'Dodoth Cultural Society',
          'Pokot Cultural Society',
          'Tepeth Cultural Society',
          'Ethur Cultural Network',
          'Karimojong Cultural Assembly',
          'Ateker Cultural Heritage Network',
        ],
      },
      {
        title: 'Kenya Cultural Systems',
        items: [
          'Kikuyu Cultural Society',
          'Luo Cultural Society (Kenya branch)',
          'Luhya Cultural Society',
          'Maasai Cultural Society',
          'Kamba Cultural Society',
          'Meru Cultural Society',
          'Kalenjin Cultural Society',
          'Turkana Cultural Society',
          'Samburu Cultural Society',
          'Swahili Coastal Cultural Society',
        ],
      },
      {
        title: 'Tanzania Cultural Systems',
        items: [
          'Chagga Cultural Society',
          'Haya Cultural Society',
          'Sukuma Cultural Society',
          'Zaramo Cultural Society',
          'Nyamwezi Cultural Society',
          'Makonde Cultural Society',
        ],
      },
      {
        title: 'West African Cultural Societies',
        items: [
          'Yoruba Cultural Society',
          'Igbo Cultural Society',
          'Hausa Cultural Society',
          'Fulani Cultural Network',
          'Akan/Ashanti Cultural Society',
          'Ewe Cultural Society',
          'Ga-Adangbe Cultural Society',
          'Dagomba Cultural Society',
          'Mande Cultural Network',
          'Bambara Cultural Society',
          'Wolof Cultural Society',
          'Serer Cultural Society',
          'Temne Cultural Society',
          'Mende Cultural Society',
          'Kanuri Cultural Society',
          'Songhai Cultural Heritage Society',
          'Ijaw Cultural Society',
          'Tiv Cultural Society',
          'Nupe Cultural Society',
        ],
      },
      {
        title: 'Central African Cultural Societies',
        items: [
          'Kongo Cultural Society',
          'Luba Cultural Society',
          'Lunda Cultural Society',
          'Chokwe Cultural Society',
          'Mongo Cultural Society',
          'Fang Cultural Society',
          'Teke Cultural Society',
          'Beti Cultural Society',
          'Azande Cultural Society',
          'Sara Cultural Society',
          'Gbaya Cultural Society',
          'Mbuti Cultural Society',
        ],
      },
      {
        title: 'Southern African Cultural Societies',
        items: [
          'Zulu Cultural Society',
          'Xhosa Cultural Society',
          'Shona Cultural Society',
          'Ndebele Cultural Society',
          'Tswana Cultural Society',
          'Sotho Cultural Society',
          'Swazi Cultural Society',
          'Venda Cultural Society',
          'Tsonga Cultural Society',
          'Herero Cultural Society',
          'Ovambo Cultural Society',
          'San/Bushmen Cultural Society',
          'Khoikhoi Cultural Society',
        ],
      },
      {
        title: 'North African Cultural Societies',
        items: [
          'Amazigh Cultural Society',
          'Kabyle Cultural Society',
          'Tuareg Cultural Society',
          'Nubian Cultural Society',
          'Coptic Cultural Society',
          'Arab-African Cultural Society',
          'Egyptian Nile Valley Cultural Society',
          'Sudanese Cultural Society',
          'Maghreb Cultural Network',
        ],
      },
      {
        title: 'Horn of Africa and Nilotic Systems',
        items: [
          'Somali Cultural Society',
          'Afar Cultural Society',
          'Oromo Cultural Society',
          'Amhara Cultural Society',
          'Tigray Cultural Society',
          'Beja Cultural Society',
          'Nilotic Cultural Society (South Sudan)',
          'Dinka Cultural Society',
          'Nuer Cultural Society',
          'Shilluk Cultural Society',
        ],
      },
      {
        title: 'Pan-African Cultural Systems',
        items: [
          'Pan-African Cultural Exchange Society',
          'African Languages and Linguistic Heritage Society',
          'Griot and Oral Traditions Society',
          'African Music and Performance Arts Society',
          'Traditional Arts and Crafts Society',
          'African Culinary Heritage Society',
          'African Fashion and Textile Society',
          'Cultural Diplomacy and Heritage Preservation Society',
          'African Naming Systems Society',
          'Traditional Governance and Chieftaincy Systems Society',
        ],
      },
      {
        title: 'Diaspora and Global African Societies',
        items: [
          'African Diaspora Cultural Society',
          'Afro-Caribbean Cultural Society',
          'Afro-Brazilian Cultural Society',
          'African-American Heritage Society',
          'Black European Cultural Network',
          'Afro-Latin American Cultural Society',
          'Global African Unity Forum',
        ],
      },
      {
        title: 'Civilisational Systems and Historical Continuities',
        items: [
          'Bantu Civilisation Network',
          'Nilotic Civilisation Society',
          'Cushitic Heritage Society',
          'Sahelian Civilisation Forum',
          'Nile Valley Civilisation Society',
          'Great Lakes Civilisation Society',
          'Horn of Africa Civilisation Society',
        ],
      },
      {
        title: 'Specialised Heritage and Knowledge Systems',
        items: [
          'African Spirituality and Cosmology Society',
          'Rites of Passage and Initiation Systems Society',
          'African Symbolism and Semiotics Society',
          'Traditional Medicine and Healing Systems Society',
          'African Architecture and Spatial Heritage Society',
          'African Maritime and Riverine Heritage Society',
          'African Resistance and Liberation Society',
          'African Festivals and Ceremonial Systems Society',
          'African Gender Systems and Social Structures Society',
          'African Migration and Diaspora History Society',
        ],
      },
      {
        title: 'Contemporary and Futures Cultural Systems',
        items: [
          'Pan-African Creative Expression Society',
          'African Film and Storytelling Society',
          'Urban African Culture and Youth Identity Society',
          'Digital African Culture and Media Society',
          'Afrofuturism and Cultural Futures Society',
          'African Literature and Intellectual Traditions Society',
          'Cultural Innovation and Creative Economy Society',
          'Pan-African Fashion Innovation Lab',
          'African Language Technology and Preservation Lab',
          'Cultural Archives and Heritage Digitisation Society',
        ],
      },
    ],
  },
  {
    id: 'clubs',
    label: 'Applied Clubs',
    eyebrow: 'Clubs and Applied Learning Systems',
    title: 'Practice-based ecosystems for capability and leadership.',
    description:
      'Clubs translate academic knowledge into experimentation, professional simulation, interdisciplinary collaboration, and real-world competence.',
    governanceTitle: 'Directorate of Student Systems and Applied Learning',
    governance: [
      'Academic oversight from corresponding colleges',
      'Approved constitution and leadership structure',
      'Activity portfolio and annual output report',
      'Institutional quality standards and annual review',
    ],
    groups: [
      {
        title: 'Science, Mathematics and Natural Systems Clubs',
        items: [
          'Mathematics and Modelling Club',
          'Physics Innovation Society',
          'Chemistry and Experimental Systems Club',
          'Biological Sciences Research Club',
          'Genetics and Genomics Innovation Hub',
          'Earth Systems Field Research Club',
          'Geoscience Exploration Society',
          'Materials Science Innovation Club',
          'Advanced Manufacturing and Prototyping Lab',
        ],
      },
      {
        title: 'Agriculture, Food and Bio-Economy Clubs',
        items: [
          'Agriculture Innovation Club',
          'Agroecology and Climate-Smart Farming Society',
          'Food Systems and Security Club',
          'Agribusiness Entrepreneurship Club',
          'Food Processing and Technology Lab',
          'Animal Science Development Club',
          'Industrial Hemp Innovation and Bioeconomy Club',
          'Bio-Based Materials Development Society',
        ],
      },
      {
        title: 'Health, Medicine and Life Sciences Clubs',
        items: [
          'Medical Students Association',
          'Clinical Practice Simulation Club',
          'Public Health Action Society',
          'Epidemiology and Disease Control Club',
          'Pharmacy Practice and Drug Development Club',
          'Biomedical Research and Diagnostics Society',
          'Laboratory Science Innovation Club',
          'Health Security and Epidemic Response Club',
          'Nutrition and Wellness Society',
        ],
      },
      {
        title: 'Engineering, Energy and Infrastructure Clubs',
        items: [
          'Civil Engineering Society',
          'Mechanical Engineering Innovation Club',
          'Electrical and Energy Systems Club',
          'Mechatronics and Robotics Engineering Club',
          'Construction and Infrastructure Development Club',
          'Renewable Energy Innovation Hub',
          'Mining and Resource Engineering Society',
          'Water Systems Engineering Club',
          'Hydrology Field Systems Club',
        ],
      },
      {
        title: 'Digital, AI and Computational Clubs',
        items: [
          'Computer Science Society',
          'Software Development and Coding Club',
          'Artificial Intelligence and Machine Learning Club',
          'Cybersecurity and Digital Defense Society',
          'Data Science and Analytics Club',
          'Information Technology Innovation Hub',
          'Blockchain and FinTech Development Club',
          'Network and Telecommunications Club',
          'Cloud Computing and Systems Engineering Club',
        ],
      },
      {
        title: 'Business, Finance and Economics Clubs',
        items: [
          'Business Leadership Society',
          'Entrepreneurship and Startup Incubation Club',
          'Finance and Investment Analysis Club',
          'Accounting and Audit Systems Society',
          'Marketing and Digital Strategy Club',
          'Banking and Financial Systems Club',
          'Trade and Supply Chain Innovation Club',
          'Cooperative Economics Development Club',
        ],
      },
      {
        title: 'Law, Governance and Policy Clubs',
        items: [
          'Law Students Society',
          'Legal Practice Simulation Club',
          'Constitutional Law and Justice Club',
          'Public Administration and Governance Society',
          'Policy Analysis and Development Lab',
          'Human Rights and Social Justice Club',
          'Diplomacy and Model African Union Club',
          'International Relations Simulation Society',
        ],
      },
      {
        title: 'Education, Humanities and Social Sciences Clubs',
        items: [
          'Education Innovation Society',
          'Teaching Practice and Curriculum Lab',
          'History and Civilisation Research Club',
          'Philosophy and Critical Thinking Society',
          'Languages and Translation Practice Club',
          'Religious Studies and Ethics Forum',
          'Indigenous Knowledge Research Circle',
          'Sociology and Social Systems Club',
          'Psychology and Behavioural Science Society',
        ],
      },
      {
        title: 'Media, Arts and Creative Industries Clubs',
        items: [
          'Journalism and Reporting Society',
          'Broadcasting and Media Production Club',
          'Film and Documentary Production Society',
          'Photography and Visual Arts Club',
          'Creative Writing and Publishing Society',
          'Music and Performance Arts Club',
          'Graphic Design and Digital Arts Club',
          'Public Relations and Strategic Communication Club',
          'Creative Economy and Cultural Entrepreneurship Club',
        ],
      },
      {
        title: 'Architecture, Urban and Environmental Clubs',
        items: [
          'Architecture Design Studio Club',
          'Urban Planning and Smart Cities Society',
          'Construction Management Club',
          'Environmental Conservation Society',
          'Climate Action and Sustainability Club',
          'Ecology and Biodiversity Research Club',
          'Climate Finance and Green Economy Club',
          'Built Environment Innovation Lab',
        ],
      },
      {
        title: 'Transport, Maritime and Global Systems Clubs',
        items: [
          'Transport Systems Engineering Club',
          'Logistics and Supply Chain Management Society',
          'Maritime Studies and Blue Economy Club',
          'Aviation and Aerospace Awareness Club',
          'Global Mobility and Infrastructure Club',
        ],
      },
      {
        title: 'Security, Peace and Strategic Studies Clubs',
        items: [
          'Security Studies Society',
          'Peacebuilding and Conflict Resolution Club',
          'Strategic Studies and Scenario Planning Forum',
          'Crisis Management Simulation Club',
          'Intelligence and Security Analysis Society',
          'Human Security and Development Club',
        ],
      },
      {
        title: 'Leadership, Innovation and Transformation Clubs',
        items: [
          'Student Parliament and Leadership Assembly',
          'Leadership Development Society',
          'Youth Policy and Advocacy Network',
          'Community Development and Service Club',
          'Social Innovation and Impact Club',
          'Ethics and Governance Leadership Forum',
        ],
      },
      {
        title: 'Global Engagement and Diplomacy Clubs',
        items: [
          'Pan-African Diplomacy Society',
          'International Relations Club',
          'Diaspora Engagement Network',
          'Global Partnerships and Exchange Club',
          'Cross-Cultural Collaboration Society',
        ],
      },
      {
        title: 'Sports, Wellness and Human Performance Clubs',
        items: [
          'University Sports Council',
          'Football Club',
          'Basketball Club',
          'Athletics and Track Society',
          'Martial Arts and Self-Defence Club',
          'Fitness and Wellness Society',
          'Psychological Resilience and Wellbeing Club',
          'Outdoor Adventure and Expedition Club',
        ],
      },
      {
        title: 'Special Strategic Clubs',
        items: [
          'Algorithmic Governance and AI Policy Club',
          'Civilisational Systems Research Club',
          'African Futures and Strategic Foresight Society',
          'Digital Sovereignty and Cyber Policy Forum',
          'Innovation Systems and Design Thinking Lab',
          'Pan-African Systems Integration Club',
        ],
      },
    ],
  },
  {
    id: 'professional',
    label: 'Professional Societies',
    eyebrow: 'Professional Societies',
    title: 'The bridge from study to recognised professional identity.',
    description:
      'Professional societies connect academic programmes to ethics, accreditation, competency benchmarking, internships, placement, CPD, and global employability.',
    governanceTitle: 'Directorate of Professional Standards and External Relations',
    governance: [
      'College-level professional boards',
      'Industry accreditation and regulatory partners',
      'Professional ethics and competency benchmarking',
      'Internship, placement, certification, and CPD alignment',
    ],
    groups: [
      { title: 'Mathematical Sciences Professional Society', items: ['Applied Mathematics Professionals Network', 'Mathematical Modelling and Systems Analysts Society', 'Pure Mathematics Scholars Association'] },
      { title: 'Physical Sciences Professional Society', items: ['Physics Professionals Association', 'Chemistry Professionals Society', 'Materials Physics Professionals Forum'] },
      { title: 'Life Sciences and Biotechnology Professional Society', items: ['Biological Sciences Professionals Network', 'Biotechnology Professionals Society', 'Microbiology Professionals Association', 'Genetics and Genomics Professionals Forum'] },
      { title: 'Earth Systems and Geosciences Professional Society', items: ['Geology Professionals Association', 'Geophysics Professionals Network', 'Earth Systems Scientists Society'] },
      { title: 'Materials Science and Manufacturing Professional Society', items: ['Materials Engineers Professional Society', 'Metallurgical Engineering Association', 'Advanced Manufacturing Professionals Network'] },
      { title: 'African Agriculture and Food Systems Professional Society', items: ['Agricultural Scientists Association', 'Agronomy and Agroecology Professionals Society', 'Animal Science Professionals Network', 'Food Sovereignty Professionals Forum'] },
      { title: 'Agribusiness and Value Chains Professional Society', items: ['Agribusiness Professionals Association', 'Food Value Chain Professionals Society', 'Agro-Industrial Systems Professionals Network'] },
      { title: 'Food Science and Nutrition Professional Society', items: ['Food Scientists Association', 'Nutrition and Dietetics Professionals Society', 'Food Technology Professionals Network'] },
      { title: 'Industrial Hemp and Bio-Economy Professional Society', items: ['Industrial Hemp Professionals Association', 'Hemp Biotechnology Professionals Network', 'Bioeconomy Systems Professionals Society'] },
      { title: 'Health Sciences and Medicine Professional Society', items: ['Medical Practitioners Society', 'Clinical Medicine Professionals Association', 'Nursing and Midwifery Professionals Network', 'Public Health Professionals Society', 'Radiography Professionals Forum'] },
      { title: 'Pharmaceutical Sciences Professional Society', items: ['Pharmacy Professionals Association', 'Pharmacology Professionals Society', 'Drug Development Professionals Network'] },
      { title: 'Biomedical and Laboratory Professional Society', items: ['Biomedical Scientists Association', 'Medical Laboratory Professionals Society', 'Biomedical Research Professionals Network'] },
      { title: 'Public Health Security and Epidemiology Society', items: ['Epidemiology Professionals Association', 'Health Security Professionals Society', 'Global Health Systems Professionals Network'] },
      { title: 'Engineering and Infrastructure Professional Society', items: ['Civil Engineers Association', 'Mechanical Engineers Society', 'Electrical Engineers Professionals Network', 'Mechatronics Engineers Society', 'Infrastructure Systems Engineers Forum'] },
      { title: 'Energy and Resource Professional Society', items: ['Renewable Energy Engineers Society', 'Petroleum Engineers Association', 'Mining Engineers Professionals Network', 'Energy Systems Engineers Society'] },
      { title: 'Water, Hydrology and Sanitation Society', items: ['Water Engineers Professional Society', 'Hydrology Professionals Association', 'Sanitation Systems Engineers Network'] },
      { title: 'Computing, AI and Digital Systems Society', items: ['Computer Science Professionals Association', 'Software Engineers Society', 'Artificial Intelligence Professionals Network', 'Cybersecurity Professionals Society', 'Data Science Professionals Forum'] },
      { title: 'Robotics and Cyber-Physical Systems Society', items: ['Robotics Engineers Association', 'Automation Systems Professionals Society', 'Intelligent Systems Engineers Network'] },
      { title: 'Digital Infrastructure and Telecommunications Society', items: ['Telecommunications Engineers Society', 'Network Systems Professionals Association', 'Digital Infrastructure Engineers Network'] },
      { title: 'Data Science and Quantitative Systems Society', items: ['Statisticians Professional Association', 'Actuarial Science Professionals Society', 'Quantitative Systems Analysts Network'] },
      { title: 'Finance, Banking and Digital Economy Society', items: ['Finance Professionals Association', 'Banking Professionals Society', 'Financial Systems Analysts Network', 'Actuarial Professionals Forum'] },
      { title: 'Business and Management Society', items: ['Business Management Professionals Association', 'Accounting Professionals Society', 'Organisational Leadership Network'] },
      { title: 'Entrepreneurship and Startup Society', items: ['Entrepreneurship Professionals Association', 'Innovation Systems Professionals Network', 'Startup Ecosystem Professionals Society'] },
      { title: 'Trade, Logistics and Supply Chains Society', items: ['Logistics Professionals Association', 'Supply Chain Professionals Society', 'International Trade Professionals Network'] },
      { title: 'Law and Justice Society', items: ['Legal Practitioners Association', 'Law Professionals Society', 'Justice Systems Professionals Network'] },
      { title: 'Digital Law and Regulation Society', items: ['Cyber Law Professionals Society', 'Technology Law Experts Network', 'Digital Governance Legal Association'] },
      { title: 'Governance and Public Administration Society', items: ['Public Administration Professionals Association', 'Governance Systems Professionals Society', 'Public Policy Analysts Network'] },
      { title: 'Diplomacy and International Relations Society', items: ['Diplomats Professional Association', 'International Relations Professionals Society', 'Global Affairs Analysts Network'] },
      { title: 'Security, Peace and Strategic Society', items: ['Security Studies Professionals Society', 'Peacebuilding Practitioners Association', 'Strategic Analysts Network'] },
      { title: 'Education and Pedagogy Society', items: ['Education Professionals Association', 'Teachers Professional Society', 'Curriculum Development Professionals Network'] },
      { title: 'Humanities and Civilisation Society', items: ['Historians Professional Society', 'Philosophy Scholars Association', 'Civilisation Studies Professionals Network'] },
      { title: 'Indigenous Knowledge Society', items: ['Indigenous Knowledge Professionals Association', 'Epistemology Systems Scholars Network', 'Traditional Systems Researchers Society'] },
      { title: 'Religion, Spirituality and Ethics Society', items: ['Theology Professionals Association', 'Ethics Professionals Society', 'Religion and Civilisation Scholars Network'] },
      { title: 'Languages and Translation Society', items: ['Linguistics Professionals Association', 'Translation Professionals Society', 'African Languages Professionals Network'] },
      { title: 'Arts and Creative Industries Society', items: ['Fine Arts Professionals Association', 'Music Professionals Society', 'Film and Creative Industries Network'] },
      { title: 'Media and Communication Society', items: ['Journalism Professionals Society', 'Media Studies Professionals Association', 'Communication Systems Professionals Network'] },
      { title: 'Architecture and Built Environment Society', items: ['Architects Professional Association', 'Quantity Surveyors Society', 'Construction Professionals Network'] },
      { title: 'Urban Futures and Smart Cities Society', items: ['Urban Planners Association', 'Smart Cities Professionals Society', 'Urban Systems Analysts Network'] },
      { title: 'Environmental Science and Ecology Society', items: ['Environmental Scientists Association', 'Ecology Professionals Society', 'Environmental Systems Analysts Network'] },
      { title: 'Climate Change and Sustainability Society', items: ['Climate Scientists Association', 'Sustainability Professionals Society', 'Climate Governance Experts Network'] },
      { title: 'Climate Economy and Carbon Systems Society', items: ['Climate Economists Association', 'Carbon Systems Professionals Society', 'Green Finance Professionals Network'] },
      { title: 'Transport and Mobility Society', items: ['Transport Engineers Association', 'Mobility Systems Professionals Society', 'Infrastructure Mobility Network'] },
      { title: 'Maritime and Blue Economy Society', items: ['Maritime Professionals Association', 'Ocean Systems Scientists Society', 'Blue Economy Experts Network'] },
      { title: 'Tourism and Cultural Economy Society', items: ['Tourism Professionals Association', 'Hospitality Industry Professionals Society', 'Cultural Economy Experts Network'] },
      { title: 'Sports Science and Human Performance Society', items: ['Sports Science Professionals Association', 'Performance Analysts Society', 'Human Performance Experts Network'] },
      { title: 'Psychology and Human Development Society', items: ['Psychologists Professional Association', 'Counselling Professionals Society', 'Behavioural Science Experts Network'] },
      { title: 'Leadership and Human Capital Society', items: ['Leadership Professionals Association', 'Human Capital Development Society', 'Institutional Leadership Network'] },
      { title: 'Space, Aerospace and Satellite Society', items: ['Aerospace Engineers Association', 'Space Systems Professionals Society', 'Satellite Technology Experts Network'] },
      { title: 'Futures and Strategic Transformation Society', items: ['Futures Studies Professionals Association', 'Strategic Foresight Experts Society', 'Civilisational Transformation Analysts Network'] },
    ],
  },
];

export const STUDENT_LIFE_DECLARATIONS = [
  'Culture is treated as a foundational system of knowledge, governance, and civilisational continuity.',
  'Clubs are applied knowledge ecosystems that transform theory into leadership capacity and real-world competence.',
  'Every academic programme should terminate in a recognised professional identity system.',
] as const;
